server:
  port: 8882
spring:
  cloud:
    nacos:
      discovery:
        server-addr: host.docker.internal:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://host.docker.internal:3306/micro-server?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    url: jdbc:mysql://host.docker.internal:3306/user?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: rr998xhz1997
  application:
    name: authorization
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: cn.piao888.user
  # 配置mapper的扫描,我到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #加载全局的配置文件
#  config-location: classpath:mapper/mybatis-config.xml
piao888:
  redirctURL: https://api.gonkamasn.com/api-user/login/authorize?redirect_uri=http://gonkamasn.com&token=
# token配置
management:
  endpoints:
    web:
      exposure:
        # 打开所有的监控点
        include: "*"